portal/apps/event_generator/urls.py
from django.conf.urls.defaults import patterns, include, url
from event_generator.views import EventDetailView, EventListView

urlpatterns = patterns('apps.gallery.views',
    url(r'^$', EventListView.as_view(), name='events'),
    url(r'^(?P<slug>[-\w]+)/$', EventDetailView.as_view(), name='event'),
)

portal/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'django.views.generic.simple.direct_to_template',
        {'template': 'index.html'}, name='home'),
    url(r'^layout/$', 'django.views.generic.simple.direct_to_template',
        {'template': 'guideline.html'}, name='layout'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'registration/login.html'}, name='login'),
    # url(r'^portal/', include('portal.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('portal.apps.blog.urls')),
    url(r'^gallery/', include('portal.apps.gallery.urls')),
    url(r'^badges/', include('portal.apps.badges.urls')),
    url(r'^encontro/', include('portal.apps.event_generator.urls')),
    url(r'^home/$', 'portal.views.home', name='home'),
)

if settings.DEBUG:
        urlpatterns += patterns('django.views.static',
                        (r'media/(?P<path>.*)', 'serve', {'document_root': settings.MEDIA_ROOT}),
                            )

portal/apps/event_generator/models.py
# -*- coding:utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.encoding import smart_unicode


class Location(models.Model):
    class Meta:
        verbose_name = u'Local'
        verbose_name_plural = u'Locais'

    description = models.CharField(u'Descrição', max_length=100)

    street = models.CharField(u'Rua', max_length=255)
    number = models.CharField(u'Número', max_length='15')
    district = models.CharField(u'Bairro', max_length='255')
    postal_code = models.CharField(u'CEP', max_length='50')
    city = models.CharField(u'Cidade', max_length=50)
    state = models.CharField(u'Estado', max_length='50')
    country = models.CharField(u'País', max_length='50')

    reference = models.CharField(u'Referência', max_length=100)

    map = models.URLField(
        u'Mapa', max_length=255, null=True, blank=True,
        help_text=u'Caso preenchido, sobrescreve o mapa gerado '
        u'automaticamente',
    )

    def __unicode__(self):
        return self.description

    @property
    def address(self):
        address = (self.street, self.number, self.district)
        return u'{0} nº{1} {2}'.format(*address)

    def get_map(self):
        if self.map:
            return self.map

        base_url = 'http://maps.google.com.br/maps?q={0}'

        qs = u'{0},{1},{2},{3},{4}'
        qs = qs.format(
            self.street, self.number, self.district, self.city, self.state,
        )

        return base_url.format(qs)


class EventLecture(models.Model):
    class Meta:
        verbose_name = u'Palestra do Evento'
        verbose_name_plural = u'Palestras do Evento'

    event = models.ForeignKey('event_generator.Event', verbose_name=u'Evento')
    lecture = models.ForeignKey('palestra.Lecture', verbose_name=u'Palestra')
    start = models.TimeField(u'Início')
    end = models.TimeField(u'Fim')

    def __unicode__(self):
        return smart_unicode(self.lecture)


class Event(models.Model):
    class Meta:
        verbose_name = u'Evento'
        verbose_name_plural = u'Eventos'

    description = models.CharField(u'Descrição', max_length=100)
    full_description = models.TextField(u'Descrição Completa')

    date = models.DateTimeField(u'Data')
    location = models.ForeignKey(
        'event_generator.Location', verbose_name=u'Local',
    )
    image = models.ImageField(upload_to='uploads/events')

    slug = models.SlugField()

    def __unicode__(self):
        return self.description

    def get_absolute_url(self):
        return reverse('event', kwargs={'slug': self.slug})

portal/apps/event_generator/views.py
from django.views.generic import DetailView, ListView
from event_generator.models import Event


class EventListView(ListView):
    model = Event
    context_object_name = u'events'


class EventDetailView(DetailView):
    model = Event
    context_object_name = u'event'

portal/templates/event_generator/event_detail.html
{% extends "base.html" %}
<p>Descrição: {{ event.description }}</p>
<p>Descrição Completa: {{ event.full_description }}</p>
<p>Data: {{ event.date }}</p>

<p>Local</p>
<p>Descrição: {{ event.location.description }}</p>
<p>Rua: {{ event.location.street }}</p>
<p>Número: {{ event.location.number }}</p>
<p>Código Postal: {{ event.location.postal_code }}</p>
<p>Cidade: {{ event.location.city }}</p>
<p>Referência: {{ event.location.reference }}</p>
<p>Mapa: {{ event.location.get_map }}</p>

{% block main_content %}
<div class="banner">
    <img src="{{ MEDIA_URL }}{{ event.image }}" alt="{{ event.description }}"  title="{{ event.description }}" />
</div>

<span>{{ event.full_description }}</span>

<span> <strong>{{ event.location.description }}, {{ event.location.address }}</strong> <br/>[ <a id="como-chegar" title="google-maps" href="#">Como chegar lá?</a> ]</span>
{# TODO: Lógica mapa #}
{# TODO: Redes sociais, sugestão: curtir específico do evento e não pug pe geral #}
{# TODO: Campo de imagem para cartas, sugestão: geração automática com PIL #}

<div class="">
    <strong>Programação</strong>
    <table cellspacing="0" cellpadding="0" class="table" id="progDias">
        <thead>
            <tr>
                <th>Início</th>
                <th>Fim</th>
                <th>Palestra</th>
                <th>Palestrante</th>
            </tr>
        </thead>
        <tbody>
            {% for event_lecture in event.eventlecture_set.all %}
            <tr id="{% cycle "001#700;485" "002#750;555" %}">
                <td>{{ event_lecture.start }}</td>
                <td>{{ event_lecture.end }}</td>
                <td>{{ event_lecture.lecture.title }}</td>
                <td>{{ event_lecture.lecture.speaker }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br/>
    {# TODO: Gerar programação completa #}
    {#<a href="Palestras.pdf">Download da programação completa</a>#}
</div>

<div class="left w960 blc_twitter">
    <script src="http://widgets.twimg.com/j/2/widget.js"></script>
    <script>
        new TWTR.Widget({
            version : 2,
            type : 'profile',
            rpp : 6,
            interval : 6000,
            width : 450,
            height : 250,
            theme : {
                shell : {
                    background : '#376a94',
                    color : '#ffffff'
                },
                tweets : {
                    background : '#fdfdfd',
                    color : '#333333',
                    links : '#376a94',
                }
            },
            features : {
                scrollbar : false,
                loop : false,
                live : false,
                hashtags : true,
                timestamp : true,
                avatars : false,
                behavior : 'all',
                id : "tblock"
            }
        }).render().setUser('pugpe').start();

    </script>
</div>


<div class="right w450">
    <div class="banner_job">
        <img src="{{ STATIC_URL }}img/event/camisetas.png" alt="Peça já sua camiseta PUG-PE" id="camisetas"/>
        <img src="{{ STATIC_URL}}img/event/canecas.png" alt="Peça já sua caneca PUG-PE" id="canecas"/>
    </div>
</div>
<div class="right w450" style="margin-top:10px;">
    <div id="fb-root"></div>
    <script>
        ( function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if(d.getElementById(id)) {
                return;
            }
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));

    </script>

    <div class="fb-comments" data-href="http://www.facebook.com/pages/Grupo-de-Usu%C3%A1rios-de-Python-de-Pernambuco-PUG-PE/213195992034947" data-num-posts="2" data-width="450"></div>
</div>
<div class="clear"></div>

<span class="title">Gostou da nossa iniciativa? Então divulgue!</span>
Escolha um dos banners abaixo e adicione ao seu site ou blogue!
<div style="text-align: center;" class="bloco_dados">
    <table width="100%" class="tabela_padrao tdcenter">
        <tbody><tr>
            <td><img alt="XVI Encontro do PUG-PE (Eu vou!)" src="img/dv1.png"/>
            <br/>
            <span class="spn-link" id="add-dvg1">Adicionar!</span></td>
            <td><img alt="XVI Encontro do PUG-PE (Eu vou!)" src="img/dv2.png"/>
            <br/>
            <span class="spn-link" id="add-dvg2">Adicionar!</span></td>
            <td><img alt="XVI Encontro do PUG-PE (Eu vou!)" src="img/dv3.png"/>
            <br/>
            <span class="spn-link" id="add-dvg3">Adicionar!</span></td>
        </tr>
    </tbody></table>
</div>

{% endblock %}

portal/templates/event_generator/event_list.html
{% extends "base.html" %}
{% block main_content %}
    {% for event in events %}
        <p>{{ event.description }}</p>
        <p><img src="{{ MEDIA_URL }}{{ event.image }}" /> {# TODO: biblioteca thubmnail #}</p>
        <p>{{ event.date }}</p>
        <p>{{ event.location.description }}</p>
        <p><a href="{% url event event.slug %}">link</a></p>
    {% empty %}
        <p>Sem eventos</p>
    {% endfor %}
{% endblock %}